services:
  # Please see for mysql docker settings here.  https://hub.docker.com/_/mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: api_database
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 5s
    # restart: always
    volumes:
      - ./external-apps/db/:/docker-entrypoint-initdb.d
    networks:
      - api-network
  web:
    image: web:latest
    container_name: web
    environment:
      DB_USER: app
      DB_PASSWORD: password
      DB_DATABASE: api_database
      DB_HOST: mysql
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    # restart: always
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://0.0.0.0:8080/health"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 3s
networks:
  api-network:
    driver: bridge
